require 'test_helper'

class TailwindTest < ActiveSupport::TestCase

  def setup
    super
    @env.register_preprocessor('text/css', Condenser::TailwindProcessor.new)
    # TODO remove unregister when default changed from SassC
    # SassC currently errors because it can't process css generated by Tailwind
    # It chokes on `@supports (color:rgb(from red r g b)) {}` which is valid css
    @env.unregister_minifier('text/css')
  end

  test 'test compilation and purge' do
    html_path = file 'index.html', <<~HTML
      <div class="border-b m-4"></div>
    HTML
    file 'main.css', <<~CSS
      @import "tailwindcss" source("#{@env.path.first}");
      @source "#{html_path}";
    CSS

    asset = assert_exported_file 'main.css', 'text/css'
    assert asset.source.include?('.border-b')
    assert asset.source.include?('.m-4')
    assert asset.source.exclude?('.p-4')
  end

end
