name: CI

on: 
  push:
  pull_request:
    types: [opened]

jobs:
  sunstone:
    name: Condenser Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4', '3.5.0-preview1']

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - run: bundle exec rake test
